### ISSUE TITLE
Typings problems

### ISSUE THREAD

**Issue by pauloo27** [Irandoust/react-trello-client#11]
Hello,

I'm using this project with TypeScript and the compiler aways complain about missing module definition.

I did a local solution by creating a `index.d.ts` in the `dist` folder of the dependency in the `node_modules` with the following content:
```ts
export const Trello: any;

const TrelloClient: any;

export default TrelloClient;
```

It's enough to fix the errors, but every time I install a new dependency I need to put this file in the dist folder again.

Do you have any solutions? 

Thanks in advance.

**Comment by pauloo27** [comment]
I created a similar file in the src folder, but with `declare module "react-trello-client"` (https://github.com/Pauloo27/homepage/commit/525768f0bd2149ed265b77f076fedf9cad1af51e). It worked. Thanks.

**Comment by Irandoust** [comment]
Sorry for the late reply and happy to hear you solved the issue. I'm working on the package improvement to include the Typescript and also adding test files. In addition, adding some new features, Please continue using the package and report the issues until the new feature version arrives. Thanks
